# Generated by Django 5.1.5 on 2025-01-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelocation',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
